### ISSUE TITLE
Flutter package?

### ISSUE THREAD

**Issue by KestasVenslauskas** [getkevin/kevin-flutter-demo#4]
Are there any plans to make it as a proper flutter package with all required data classes & automatic integrations?

**Comment by edgar-zigis** [comment]
@KestasVenslauskas we have started working on it yesterday as we got a Flutter newcomer joined us this week. Will have it done sometimes next week. Will notify you here.

**Comment by KestasVenslauskas** [comment]
@edgar-zigis Any progress on that?

**Comment by edgar-zigis** [comment]
@KestasVenslauskas our Flutter engineer went on vacations for 2 weeks and just got back today. He is already finishing the plugin, will provide further updates here.

**Comment by edgar-zigis** [comment]
@KestasVenslauskas please check [this](https://github.com/getkevin/kevin-flutter).
